version: "2"
linters:
  enable:
    - errname
    - errorlint
    - gocritic
    - misspell
    - revive
  settings:
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - text: "var-naming: avoid meaningless package names"
        linters:
          - revive
      - path: _test\.go
        linters:
          - errcheck
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
