version: "3"

tasks:
  task:download:
    desc: "Download the latest Taskfile binary"
    cmd: |-
      Go to https://taskfile.dev/installation to download/upgrade taskfile (a task runner).
      If you are running this, you already have taskfile, but this is here for
      anyone who looks at the Taskfile.yaml first to see what it is

  init:
    desc: "Initialize development environment (pre-commit)"
    cmd: pre-commit install

  tidy:
    desc: "Run go mod tidy"
    cmd: go mod tidy

  lint:
    desc: "Run golangci-lint"
    cmd: golangci-lint run

  clean:
    desc: "Clean build artifacts"
    cmds:
      - cmd: rm -rf dist coverage.txt
        platforms: [ linux, darwin ]
      - cmd: pwsh -Command 'Remove-Item -Path dist,coverage.txt -Recurse -Force'
        platforms: [ windows ]

  build:
    desc: "Build the CLI"
    sources:
      - "cmd/yutc/*.go"
      - "internal/**/*.go"
      - "pkg/**/*.go"
      - "go.mod"
      - "go.sum"
    cmds:
      - platforms: [ windows ]
        cmd: |-
          go build -o ./dist/yutc.exe ./cmd/yutc
      - platforms: [ linux, darwin ]
        cmd: |-
          go build -o ./dist/yutc ./cmd/yutc

  install:
    desc: "Install the CLI"
    cmd: "go install ./cmd/yutc"

  docs:render:
    desc: "Render the docs"
    run: always
    cmd: |-
      go run ./cmd/yutc \
        --overwrite \
        --output README.md \
        --data ./docs/_data/README.data.yaml \
        ./docs/_templates/README.md.tmpl

  run:
    desc: "Run yutc"
    run: always
    cmd: |-
      go run ./cmd/yutc {{ .CLI_ARGS }}

  run:help:
    desc: "Run yutc --help"
    run: always
    cmd: |-
      go run ./cmd/yutc --help

  run:tests:
    desc: "Run go tests"
    run: always
    cmd: |-
      go test -count=1 ./...

  version:get:
    desc: "Get the current version"
    cmd: go run ./cmd/yutc --version

  version:set:
    desc: "Set the version in pkg/version.go (usage: task version:set VERSION=1.2.3)"
    cmds:
    - platforms: [ windows ]
      cmd: |-
        pwsh -Command '
        if ("{{.VERSION}}" -eq "") {
            Write-Error "VERSION parameter is required"
            exit 1
        }
        (Get-Content pkg/version.go) -replace "var version = `".*`"", "var version = `"{{.VERSION}}`"" | Set-Content pkg/version.go
        Write-Host "Version set to {{.VERSION}}"
        '
    - platforms: [ linux, darwin ]
      cmd: |-
        if [ -z "{{.VERSION}}" ]; then
            echo "VERSION parameter is required"
            exit 1
        fi
        sed -i.bak 's/var version = ".*"/var version = "{{.VERSION}}"/' pkg/version.go
        rm pkg/version.go.bak
        echo "Version set to {{.VERSION}}"

  go:coverage:
    desc: "Run test coverage and open report"
    cmds:
      - go test -coverprofile=coverage.txt ./...
      - go tool cover -html=coverage.txt
