version: "3"

tasks:
  download-taskfile:
    desc: "Download the latest Taskfile binary"
    cmd: |-
      Go to https://taskfile.dev/installation to download/upgrade taskfile (a task runner).
      If you are running this, you already have taskfile, but this is here for
      anyone who looks at the Taskfile.yaml first to see what it is

  build:
    desc: "Build the CLI"
    sources:
      - "cmd/yutc/*.go"
      - "pkg/**/*.go"
      - "internal/**/*.go"
      - "go.mod"
    cmd: "go build -o ./dist ./cmd/yutc"

  install:
    desc: "Install the CLI"
    cmd: "go install ./cmd/yutc"

  render-docs:
    desc: "Render the docs"
    run: always
    cmd: |-
      go run ./cmd/yutc \
        --overwrite \
        --output README.md \
        --data ./docs/_data/README.data.yaml \
        ./docs/_templates/README.md.tmpl

  run-help:
    desc: "Run yutc --help"
    run: always
    cmd: |-
      go run ./cmd/yutc/yutc.go --help

  run-tests:
    desc: "Run go tests"
    run: always
    cmd: |-
      go test -count=1 ./...
